INSERT INTO SEGMENT (SEGMENT_NAME, CREDIT_MODIFIER) VALUES ('segment 1', '100');
INSERT INTO SEGMENT (SEGMENT_NAME, CREDIT_MODIFIER) VALUES ('segment 2', '300');
INSERT INTO SEGMENT (SEGMENT_NAME, CREDIT_MODIFIER) VALUES ('segment 3', '1000');

INSERT INTO USERS (PERSONAL_CODE, USER_NAME, USER_SURNAME, DEBT, SEGMENT_ID) VALUES ('49002010965', 'Name0', 'Surname0', '1',
(SELECT SEGMENT_ID FROM SEGMENT WHERE SEGMENT_NAME = 'segment 1'));
INSERT INTO USERS (PERSONAL_CODE, USER_NAME, USER_SURNAME, SEGMENT_ID) VALUES ('49002010976', 'Name1', 'Surname1',
(SELECT SEGMENT_ID FROM SEGMENT WHERE SEGMENT_NAME = 'segment 1'));
INSERT INTO USERS (PERSONAL_CODE, USER_NAME, USER_SURNAME, SEGMENT_ID) VALUES ('49002010987', 'Name2', 'Surname2',
(SELECT SEGMENT_ID FROM SEGMENT WHERE SEGMENT_NAME = 'segment 2'));
INSERT INTO USERS (PERSONAL_CODE, USER_NAME, USER_SURNAME, SEGMENT_ID) VALUES ('49002010998', 'Name3', 'Surname3',
(SELECT SEGMENT_ID FROM SEGMENT WHERE SEGMENT_NAME = 'segment 3'));