INSERT INTO SEGMENT (SEGMENT_NAME, CREDIT_MODIFIER) VALUES ('segment 1', '100');
INSERT INTO SEGMENT (SEGMENT_NAME, CREDIT_MODIFIER) VALUES ('segment 2', '300');
INSERT INTO SEGMENT (SEGMENT_NAME, CREDIT_MODIFIER) VALUES ('segment 3', '1000');

INSERT INTO USERS (PERSONAL_CODE) VALUES ('49002010965');
INSERT INTO USERS (PERSONAL_CODE) VALUES ('49002010976');