CREATE TABLE USERS(
  USER_ID BIGSERIAL PRIMARY KEY,
  PERSONAL_CODE VARCHAR(11) NOT NULL UNIQUE
);

CREATE TABLE SEGMENT(
  SEGMENT_ID BIGSERIAL PRIMARY KEY,
  SEGMENT_NAME VARCHAR(11) NOT NULL UNIQUE,
  CREDIT_MODIFIER BIGINT NOT NULL
);